# safelist
#branches:
#  only:
#    - master
language: bash

services:
  - docker

before_install:
  - docker pull hubbitus/latex
script:
  - docker run --rm  -it -v $(pwd)/Text:/source/Text hubbitus/latex bash -c 'cd Text; xelatex -synctex=1 -interaction=nonstopmode main.tex'

deploy:
  - provider: releases
    api_key: $TOKEN
    file: "Text/main.pdf"
    skip_cleanup: true
    on:
      branch: master
