# safelist
branches:
  only:
  - master
language: ruby  

services:
  - docker

before_install:
  - docker pull niccokunzmann/ci-latex

script:
  - docker run -v "`pwd`:/thesis" --rm -it niccokunzmann/ci-latex  bash -c 'cd Text; xelatex -synctex=1 -interaction=nonstopmode main.tex'

deploy:
  provider: releases
  api_key: $TOKEN
  file: "Text/main.pdf"
  skip_cleanup: true
  on:
    branch: master