dist: xenial
# safelist
branches:
  only:
  - master
cache:
    - apt
before_install:
    - sudo apt-get update
    - sudo apt-get install -y texlive texlive-xetex texlive-latex3 texlive-lang-cyrillic texlive-latex-extra texlive-bibtex-extra biber ttf-mscorefonts-installer texlive-fonts-recommended texlive-fonts-extra
script:
    - cd Text   
    - bash ./run.sh
    - cd ..
deploy:
  provider: releases
  api_key: $TOKEN
  file: "Text/main.pdf"
  skip_cleanup: true
